services:
  trino:
    env_file: "./trino.env"
    hostname: trino-worker
    #ports:
      #- "9080:8080"
      #- "9043:8443"
    image: "trinodb/trino:472"
    container_name: trino_worker
    networks:
     - network_test
    restart: unless-stopped
    volumes:
      - ./etc:/etc/trino
    extra_hosts:
        - "host.docker.internal:host-gateway"
        - "trino-coordinator:10.128.15.220"
networks:
  network_test:
    name: network_test
    external: true
